export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CREATE_NEW_POST = 'CREATE_NEW_POST';

export const FETCH_POSTS_REQUESTED = 'FETCH_POSTS_REQUESTED';
export const FETCH_POST_FULFILLED = 'FETCH_POST_FULFILLED';
export const FETCH_POST_REJECTED = 'FETCH_POST_REJECTED';